### ISSUE TITLE
Enable All BibleHub Translations

### ISSUE THREAD

**Issue by Tadukoo** [Tadukoo/TadukooBible#18]
The goal here is to add all the translations that BibleHub includes to be available in Tadukoo Bible. Some of these are technically already included as this is being written, but this will be ongoing for a while probably due to inconsistencies on BibleHub's site (and due to what gets prioritized for Tadukoo Bible)

**The Translations**
- [ ] A Faithful Version (AFV)
- [ ] American Standard Version (ASV)
- [ ] Amplified Bible (AMP)
- [ ] Anderson New Testament (Anderson)
- [ ] Berean Literal Bible (BLB)
- [ ] Berean Reader's Bible (BRB)
- [ ] Berean Study Bible (BSB)
- [ ] Bishop's Bible of 1568 (Bishop's)
- [ ] Brenton's Septuagint (BSEP)
- [ ] Catholic Public Domain Version (CPDV)
- [ ] Christian Standard Bible (CSB)
- [ ] Contemporary English Version (CEV)
- [ ] Coverdale Bible of 1535 (Coverdale)
- [ ] Darby Translation (DARBY)
- [ ] Douay-Rheims 1899 American Edition (DRA)
- [ ] English Standard Version (ESV)
- [ ] 1599 Geneva Bible (GNV)
- [ ] GOD'S WORD Translation (GW)
- [ ] Godbey New Testament (Godbey)
- [ ] Good News Translation (GNT)
- [ ] Haweis New Testament (Haweis)
- [ ] Holman Christian Standard Bible (HCSB)
- [ ] Institute for Scripture Research (ISR)
- [ ] International Standard Version (ISV)
- [ ] JPS Tanakh 1917 (JPS)
- [ ] King James Version (KJV)
- [ ] King James 2000 Bible (KJ2000)
- [ ] American King James Version (AKJV)
- [ ] King James Bible: Purple Letter Edition (KJP)
- [ ] Lamsa Bible (LAMSA)
- [ ] Literal Emphasis Translation (LET)
- [ ] Literal Standard Version (LSV)
- [ ] Mace New Testament (Mace)
- [ ] New American Bible (Revised Edition) (NABRE)
- [ ] New American Standard Bible (NASB)
- [ ] New American Standard Bible 1995 (NASB95)
- [ ] New American Standard Bible 1977 (NASB77)
- [ ] New English Translation (NET)
- [ ] New Heart English Bible (NHEB)
- [ ] New International Version (2011)
- [ ] New King James Version (NKJV)
- [ ] New Living Translation (NLT)
- [ ] New Revised Standard Version Catholic Edition (NRSVCE)
- [ ] Orthodox Jewish Bible (OJB)
- [ ] The Peshitta Holy Bible Translated (HPBT)
- [ ] Revised Version (RV)
- [ ] Smith's Literal Translation (SLT)
- [ ] Tyndale Bible of 1526 (Tyndale)
- [ ] Tyndale New Testament (TNT)
- [ ] Webster's Bible Translation (WBT)
- [ ] Weymouth New Testament (WEY)
- [ ] World English Bible (WEB)
- [ ] Worrell New Testament (WOR)
- [ ] Worsley New Testament (Worsley)
- [ ] Wycliffe Bible (WYC)
- [ ] Young's Literal Translation (YLT)

**Comment by Tadukoo** [comment]
Changing to be generic for all BibleHub Translations as an Epic instead of the partial translations as previously listed.
