### ISSUE TITLE
[MODULE] Tadukoo Bible API

### ISSUE THREAD

**Issue by Tadukoo** [Tadukoo/TadukooBible#21]
Make the Tadukoo Bible API Module

**Changes TODO**
- [ ] Create Constants
  - [ ] BibleBooks enum
  - [ ] ApocryphaBooks enum
  - [ ] Translations enum
- [ ] Create Pojo classes
  - [ ] BibleReference
- [ ] Create Bible Verse Storage
  - [ ] VerseStorage interface
  - [ ] VerseFileStorage
  - [ ] VerseDatabaseStorage
- [ ] Create Bible Downloading
  - [ ] Retrievals by Chapter (#22)
    - [ ] Retrieval from BibleHub
    - [ ] Retrieval from BibleGateway
  - [ ] Parallel runner to download a translation
- [ ] Create a Settings class
  - [ ] Make it able to be converted to/from JSON
  - [ ] Contains Verse Storage option
  - [ ] Contains Verse Retrieval option
- [ ] Create Verse Retrieval (For retrieving verses/chapters/books at a time from wherever they've been stored)

**Comment by Tadukoo** [comment]
Note: This is being worded as creating the entire module even though a bunch of work has been done on it. The goal is to make sure everything gets improved / javadoc'd / tested as needed

**Comment by Tadukoo** [comment]
Something that needs added/changed in this is the Settings for the Verse Retrieval option, to make it on a per translation basis (e.g. so that we could specify to download from BibleGateway for some translations, and BibleHub for others, since they have different translations available on their sites)

**Comment by Tadukoo** [comment]
It might make sense to have translations be a part of the Settings entirely instead of having an enum, that way people could have more customization more easily that way. With that in mind, it may also make sense to make the retrievals more generic to be able to be file based to not have to write a new class for each site / regex that comes up

**Comment by Tadukoo** [comment]
It also might make sense to make a more generic Reference pojo that can have both an apocrypha or bible reference. Could either be just a single reference class or do an extension thing (having BibleReference and ApocryphaReference extend the generic Reference)
